name = 'spring-resonance-73fd'
compatibility_date = "2026-02-05"

# Aquí es donde configuras el directorio de los archivos estáticos
[build]
  command = "npm run build"  # Si no tienes una construcción previa, puedes dejar esto vacío

[[deploy]]
  # Aquí es donde se especifica la ruta de los archivos estáticos
  assets = { directory = "./" }

# Puedes añadir más configuraciones si es necesario, pero no necesitas "deploy" como campo.
